package com.grocerylistbuilder.core.extract.crf

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Test

/** Differential tests: fixtures generated by running the real `ingredient_parser_nlp` Python
 * library (see scripts/generate_android_crf_resources.py's sibling fixture generation), so these
 * confirm the Kotlin port matches the exact tokenizer/stemmer the CRF model was trained against. */
class TokenizerStemmerTest {

    private val fixtures = Json.parseToJsonElement(
        TokenizerStemmerTest::class.java.getResourceAsStream("/crf_fixtures/tokenizer_stemmer.json")!!
            .bufferedReader().readText(),
    ).jsonObject

    @Test
    fun `tokenize matches Python for real ingredient lines`() {
        val cases = fixtures["tokenize"]!!.jsonObject
        for ((line, expectedTokens) in cases) {
            val expected = expectedTokens.jsonArray.map { it.jsonPrimitive.content }
            assertEquals("tokenize(\"$line\")", expected, Tokenizer.tokenize(line))
        }
    }

    @Test
    fun `stem matches Python for real ingredient words`() {
        val cases = fixtures["stem"]!!.jsonObject
        for ((word, expectedStem) in cases) {
            assertEquals("stem(\"$word\")", expectedStem.jsonPrimitive.content, Stemmer.stem(word))
        }
    }
}
