package com.grocerylistbuilder.core.extract.crf

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.double
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.util.zip.GZIPInputStream

/** Loads the gzipped JSON resources generated by `scripts/generate_android_crf_resources.py`
 * (see `core/src/main/resources/ingredient_parser/`). Plain Java resources rather than Android
 * assets, so this works identically in `:core:test` (JVM) and on-device — no `Context` needed,
 * keeping `:core` Android-free. */
internal object ResourceData {
    private val json = Json { ignoreUnknownKeys = true }

    fun readJson(resourceName: String): JsonElement {
        val stream = ResourceData::class.java.getResourceAsStream("/ingredient_parser/$resourceName")
            ?: error("Missing resource: ingredient_parser/$resourceName")
        val text = GZIPInputStream(stream).bufferedReader(Charsets.UTF_8).use { it.readText() }
        return json.parseToJsonElement(text)
    }

    fun readJsonObject(resourceName: String): JsonObject = readJson(resourceName).jsonObject

    fun stringMap(obj: JsonObject): Map<String, String> =
        obj.mapValues { it.value.jsonPrimitive.content }

    /** Like [stringMap], but preserves JSON `null` values as Kotlin `null` (vs. throwing) —
     * needed for tables like unit canonicalization where `null` is a meaningful "not recognized"
     * value distinct from "not present at all". */
    fun nullableStringMap(obj: JsonObject): Map<String, String?> =
        obj.mapValues { if (it.value == JsonNull) null else it.value.jsonPrimitive.content }

    fun stringList(element: JsonElement): List<String> =
        element.jsonArray.map { it.jsonPrimitive.content }

    fun doubleWeightMap(obj: JsonObject): Map<String, Map<String, Double>> =
        obj.mapValues { (_, labelWeights) ->
            labelWeights.jsonObject.mapValues { it.value.jsonPrimitive.double }
        }

    fun intMap(obj: JsonObject): Map<String, Int> = obj.mapValues { it.value.jsonPrimitive.int }

    fun flatDoubleMap(obj: JsonObject): Map<String, Double> = obj.mapValues { it.value.jsonPrimitive.double }

    fun double(element: JsonElement): Double = element.jsonPrimitive.double
}
